export let products = [
  {
    title: "Memoria Kingston FURY DDR4",
    maker: "Kingston",
    price: 33500,
    description:
      "Capacidad: 8GB * Perfil de memoria: 3200MT/s 16-18-18 1.35V * Número de parte: KF432C16BB/8",
    img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547007/RAMkingstonFURY_zlpqkr.jpg",
    stock: 10,
    category: "Memorias",
    subcategory: "DIMM",
  },
  {
    title: "Memoria Kingston FURY DDR4",
    maker: "Kingston",
    price: 62500,
    description:
      "Capacidad: 16GB * Perfil de memoria: 3200MT/s 16-18-18 1.35V * Número de parte: KF432C16BB1/16",
    img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547007/RAMkingstonFURY_zlpqkr.jpg",
    stock: 8,
    category: "Memorias",
    subcategory: "DIMM",
  },
  {
    title: "Memoria Kingston DDR4 SODIMM",
    maker: "Kingston",
    price: 19900,
    description:
      "Capacidad: 4GB * Perfil de memoria: 2666MT/s 19-16-16 1.2V * Número de parte: KVR26S19S6/4",
    img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547007/RAMkingstonSODIMM_bjsdix.jpg",
    stock: 16,
    category: "Memorias",
    subcategory: "SODIMM",
  },
  {
    title: "Memoria Kingston DDR4 SODIMM",
    maker: "Kingston",
    price: 35500,
    description:
      "Capacidad: 8GB * Perfil de memoria: 2666MT/s 19-16-16 1.2V * Número de parte: KVR26S19S6/8",
    img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547007/RAMkingstonSODIMM_bjsdix.jpg",
    stock: 20,
    category: "Memorias",
    subcategory: "SODIMM",
  },
  {
    title: "Memoria Kingston DDR4 SODIMM",
    maker: "Kingston",
    price: 57300,
    description:
      "Capacidad: 16GB * Perfil de memoria: 2666MT/s 19-16-16 1.2V * Número de parte: KVR26S19S8/16",
    img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547007/RAMkingstonSODIMM_bjsdix.jpg",
    stock: 12,
    category: "Memorias",
    subcategory: "SODIMM",
  },
  {
    title: "SSD Kingston NV2 PCIe 4.0",
    maker: "Kingston",
    price: 32000,
    description:
      "Capacidad: 250GB * PCIe NVMe Gen 4x4 * Hasta 3.000MB/seg Lectura, 1.300MB/seg Escritura * Número de parte: SNV2S/250G",
    img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547007/SSDKingstonNV2_bwcspj.jpg",
    stock: 15,
    category: "Discos",
    subcategory: "SSD",
  },
  {
    title: "SSD Kingston NV2 PCIe 4.0",
    maker: "Kingston",
    price: 70000,
    description:
      "Capacidad: 500GB * PCIe NVMe Gen 4x4 * Hasta 3.500MB/seg Lectura, 2.100MB/seg Escritura * Número de parte: SNV2S/500G",
    img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547007/SSDKingstonNV2_bwcspj.jpg",
    stock: 19,
    category: "Discos",
    subcategory: "SSD",
  },
  {
    title: "SSD A400 SATA",
    maker: "Kingston",
    price: 46200,
    description:
      "Capacidad: 240GB * SATA Rev 3.0 * Hasta 500MB/seg Lectura, 350MB/seg Escritura * Número de parte: SA400S37/240G",
    img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547008/SSDKingstonSATA_mhbrq8.jpg",
    stock: 19,
    category: "Discos",
    subcategory: "SSD",
  },
  {
    title: "SSD A400 SATA",
    maker: "Kingston",
    price: 73000,
    description:
      "Capacidad: 480GB * SATA Rev 3.0 * Hasta 500MB/seg Lectura, 450MB/seg Escritura * Número de parte: SA400S37/480G",
    img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547008/SSDKingstonSATA_mhbrq8.jpg",
    stock: 19,
    category: "Discos",
    subcategory: "SSD",
  },
  {
    title: "SSD WD green SN350 NVMe",
    maker: "Western Digital",
    price: 36200,
    description:
      "Capacidad: 250GB * PCIe Gen 4.0 * Velocidades de lectura hasta 2400 MB/s * Número de parte: WDS250G2G0C",
    img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547008/WDGreenNVMe_agqwzd.png",
    stock: 12,
    category: "Discos",
    subcategory: "SSD",
  },
  {
    title: "SSD WD blue SN580 NVMe",
    maker: "Western Digital",
    price: 60200,
    description:
      "Capacidad: 250GB * PCIe Gen 4.0 * Velocidades de lectura hasta 4150 MB/s * Número de parte: WDS250G3B0E",
    img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547007/WDBlueNVMe_nrxk1z.webp",
    stock: 5,
    category: "Discos",
    subcategory: "SSD",
  },
  {
    title: "SSD WD Green SATA",
    maker: "Western Digital",
    price: 73000,
    description:
      "Capacidad: 240GB * SATA Rev 3.0 * Hasta 545MB/s Lectura * Número de parte: WDS240G3G0A",
    img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547006/SSDWDGreenSATA_km6pze.jpg",
    stock: 10,
    category: "Discos",
    subcategory: "SSD",
  },
  {
    title: "HDD WD Blue PC Desktop",
    maker: "Western Digital",
    price: 105000,
    description:
      "Capacidad: 1TB * 7200 RPM * Tamaño: 3.5-Inch * Transferencia: up to 150MB/s * Número de parte: WD10EZEX",
    img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718550125/HDDWDBluePC_sl3wjq.jpg",
    stock: 11,
    category: "Discos",
    subcategory: "HDD",
  },
  {
    title: "HDD WD Blue Notebook",
    maker: "Western Digital",
    price: 85200,
    description:
      "Capacidad: 1TB * 5400 RPM * Tamaño: 2.5-Inch * Transferencia: up to 150MB/s * Número de parte: WD10SPZX",
    img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718550125/HDDWDBlueNotebook_qlsexe.webp",
    stock: 8,
    category: "Discos",
    subcategory: "HDD",
  },
  {
    title: "Genius KB 116 Black",
    maker: "Genius",
    price: 24000,
    description:
      "Diseño del Teclado: Estándar * Interfaz: USB * Distribución: Español * Dimensiones: 435 x 135 x 20,5 mm * Peso: 440g",
    img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547687/GeniusKB116_lrify8.bmp",
    stock: 10,
    category: "Perifericos",
    subcategory: "Teclados",
  },
  {
    title: "Genius KB 117 Black",
    maker: "Genius",
    price: 20000,
    description:
      "Diseño del Teclado: Estándar * Interfaz: USB * Distribución: Español * Dimensiones: 440,51 x 139,67 x 20,07 mm * Peso: 450g",
    img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1719866635/GeniusK117_xrzjxr.png",
    stock: 10,
    category: "Perifericos",
    subcategory: "Teclados",
  },
  {
    title: "Redragon Draconic Pro Inalámbrico",
    maker: "Redragon",
    price: 73000,
    description:
      "Diseño del Teclado: Compacto 60% * Interfaz: Inalámbrica (Bluetooth 5.0) * Distribución: Ingles * Dimensiones: 29,17 X 10,17 X 3,6 cm * Switches: Redragon Brown",
    img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718548378/RedragondraconicPro_fow2zz.png",
    stock: 4,
    category: "Perifericos",
    subcategory: "Teclados",
  },
  {
    title: "Redragon K552 Kumara",
    maker: "Redragon",
    price: 57000,
    description:
      "Diseño del Teclado: Tenkeyless 80% * Interfaz: USB * Distribución: Español * Dimensiones: 37,5 X 15,5 X 4,3 cm * Switches: Outemu Blue",
    img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718548934/RedragonK552Kumara_imhnxt.jpg",
    stock: 5,
    category: "Perifericos",
    subcategory: "Teclados",
  },
  {
    title: "Logitech G213",
    maker: "Logitech",
    price: 93500,
    description:
      "Diseño del Teclado: Estándar * Interfaz: USB 2.0 * Distribución: Español * Dimensiones: 452 X 218 X 33 mm * Peso: 1000g",
    img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718549297/LogitechG213_qbera1.jpg",
    stock: 3,
    category: "Perifericos",
    subcategory: "Teclados",
  },
  {
    title: "Genius DX-110",
    maker: "Genius",
    price: 6450,
    description:
      "Sensor: óptico * Interfaz: cable USB * Largo cable: 1.5m * Resolución: 1000 dpi * Dimensiones: 105 x 60 x 37 mm * Peso: 85g",
    img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718551115/GeniusDX110_kumj4p.jpg",
    stock: 10,
    category: "Perifericos",
    subcategory: "Mouses",
  },
  {
    title: "Logitech M280",
    maker: "Logitech",
    price: 19500,
    description:
      "Conexión: inalámbrica 2.4Ghz * Sensor: Láser * Pilas: 1 AA * Resolución: 1000 dpi * Dimensiones: 105,4 x 67,9 x 38,4 mm * Peso: 91,0g",
    img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718551115/LogitechM280_eroggb.jpg",
    stock: 12,
    category: "Perifericos",
    subcategory: "Mouses",
  },
];
