export let products = [
    {
        id: 1,
        title: "Memoria Kingston FURY DDR4",
        maker: "Kingston",
        price: 33500,
        description: "Capacidad: 8GB\nPerfil de memoria: 3200MT/s 16-18-18 1.35V\nNúmero de parte: KF432C16BB/8",
        img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547007/RAMkingstonFURY_zlpqkr.jpg",
        stock: 10,
        category: "Memorias",
        subcategory: "DIMM",
    },
    {
        id: 2,
        title: "Memoria Kingston FURY DDR4",
        maker: "Kingston",
        price: 62500,
        description: "Capacidad: 16GB\nPerfil de memoria: 3200MT/s 16-18-18 1.35V\nNúmero de parte: KF432C16BB1/16",
        img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547007/RAMkingstonFURY_zlpqkr.jpg",
        stock: 8,
        category: "Memorias",
        subcategory: "DIMM",
    },
    {
        id: 3,
        title: "Memoria Kingston DDR4 SODIMM",
        maker: "Kingston",
        price: 19900,
        description: "Capacidad: 4GB\nPerfil de memoria: 2666MT/s 19-16-16 1.2V\nNúmero de parte: KVR26S19S6/4",
        img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547007/RAMkingstonSODIMM_bjsdix.jpg",
        stock: 16,
        category: "Memorias",
        subcategory: "SODIMM",
    },
    {
        id: 4,
        title: "Memoria Kingston DDR4 SODIMM",
        maker: "Kingston",
        price: 35500,
        description: "Capacidad: 8GB\nPerfil de memoria: 2666MT/s 19-16-16 1.2V\nNúmero de parte: KVR26S19S6/8",
        img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547007/RAMkingstonSODIMM_bjsdix.jpg",
        stock: 20,
        category: "Memorias",
        subcategory: "SODIMM",
    },
    {
        id: 5,
        title: "Memoria Kingston DDR4 SODIMM",
        maker: "Kingston",
        price: 57300,
        description: "Capacidad: 16GB\nPerfil de memoria: 2666MT/s 19-16-16 1.2V\nNúmero de parte: KVR26S19S8/16",
        img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547007/RAMkingstonSODIMM_bjsdix.jpg",
        stock: 12,
        category: "Memorias",
        subcategory: "SODIMM",
    },
    {
        id: 6,
        title: "SSD Kingston NV2 PCIe 4.0",
        maker: "Kingston",
        price: 32000,
        description: "Capacidad: 250GB\nPCIe NVMe Gen 4x4\nHasta 3.000MB/seg Lectura, 1.300MB/seg Escritura\nNúmero de parte: SNV2S/250G",
        img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547007/SSDKingstonNV2_bwcspj.jpg",
        stock: 15,
        category: "Discos",
        subcategory: "SSD",
    },
    {
        id: 7,
        title: "SSD Kingston NV2 PCIe 4.0",
        maker: "Kingston",
        price: 70000,
        description: "Capacidad: 500GB\nPCIe NVMe Gen 4x4\nHasta 3.500MB/seg Lectura, 2.100MB/seg Escritura\nNúmero de parte: SNV2S/500G",
        img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547007/SSDKingstonNV2_bwcspj.jpg",
        stock: 19,
        category: "Discos",
        subcategory: "SSD",
    },
    {
        id: 8,
        title: "SSD A400 SATA",
        maker: "Kingston",
        price: 46200,
        description: "Capacidad: 240GB\nSATA Rev 3.0\nHasta 500MB/seg Lectura, 350MB/seg Escritura\nNúmero de parte: SA400S37/240G",
        img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547008/SSDKingstonSATA_mhbrq8.jpg",
        stock: 19,
        category: "Discos",
        subcategory: "SSD",
    },
    {
        id: 9,
        title: "SSD A400 SATA",
        maker: "Kingston",
        price: 73000,
        description: "Capacidad: 480GB\nSATA Rev 3.0\nHasta 500MB/seg Lectura, 450MB/seg Escritura\nNúmero de parte: SA400S37/480G",
        img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547008/SSDKingstonSATA_mhbrq8.jpg",
        stock: 19,
        category: "Discos",
        subcategory: "SSD",
    },
    {
        id: 10,
        title: "SSD WD green SN350 NVMe",
        maker: "Western Digital",
        price: 36200,
        description: "Capacidad: 250GB\nPCIe Gen 4.0\nVelocidades de lectura hasta 2400 MB/s\nNúmero de parte: WDS250G2G0C",
        img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547008/WDGreenNVMe_agqwzd.png",
        stock: 12,
        category: "Discos",
        subcategory: "SSD",
    },
    {
        id: 11,
        title: "SSD WD blue SN580 NVMe",
        maker: "Western Digital",
        price: 60200,
        description: "Capacidad: 250GB\nPCIe Gen 4.0\nVelocidades de lectura hasta 4150 MB/s\nNúmero de parte: WDS250G3B0E",
        img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547007/WDBlueNVMe_nrxk1z.webp",
        stock: 5,
        category: "Discos",
        subcategory: "SSD",
    },
    {
        id: 12,
        title: "SSD WD Green SATA",
        maker: "Western Digital",
        price: 73000,
        description: "Capacidad: 240GB\nSATA Rev 3.0\nHasta 545MB/s Lectura\nNúmero de parte: WDS240G3G0A",
        img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547006/SSDWDGreenSATA_km6pze.jpg",
        stock: 10,
        category: "Discos",
        subcategory: "SSD",
    },
    {
        id: 13,
        title: "HDD WD Blue PC Desktop",
        maker: "Western Digital",
        price: 105000,
        description: "Capacidad: 1TB\n7200 RPM\nTamaño: 3.5-Inch\nTransferencia: up to 150MB/s\nNúmero de parte: WD10EZEX",
        img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718550125/HDDWDBluePC_sl3wjq.jpg",
        stock: 11,
        category: "Discos",
        subcategory: "HDD",
    },
    {
        id: 14,
        title: "HDD WD Blue Notebook",
        maker: "Western Digital",
        price: 85200,
        description: "Capacidad: 1TB\n5400 RPM\nTamaño: 2.5-Inch\nTransferencia: up to 150MB/s\nNúmero de parte: WD10SPZX",
        img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718550125/HDDWDBlueNotebook_qlsexe.webp",
        stock: 8,
        category: "Discos",
        subcategory: "HDD",
    },
    {
        id: 15,
        title: "Genius KB 116 Black",
        maker: "Genius",
        price: 24000,
        description: "Diseño del Teclado: Estándar\nInterfaz: USB\nDistribución: Español\nDimensiones: 435 x 135 x 20,5 mm\nPeso: 440g",
        img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547687/GeniusKB116_lrify8.bmp",
        stock: 10,
        category: "Perifericos",
        subcategory: "Teclados",
    },
    {
        id: 16,
        title: "Genius KB 117 Black",
        maker: "Genius",
        price: 20000,
        description: "Diseño del Teclado: Estándar\nInterfaz: USB\nDistribución: Español\nDimensiones: 440,51 x 139,67 x 20,07 mm\nPeso: 450g",
        img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718547006/SSDWDGreenSATA_km6pze.jpg",
        stock: 10,
        category: "Perifericos",
        subcategory: "Teclados",
    },
    {
        id: 17,
        title: "Redragon Draconic Pro Inalámbrico",
        maker: "Redragon",
        price: 73000,
        description: "Diseño del Teclado: Compacto 60%\nInterfaz: Inalámbrica (Bluetooth 5.0)\nDistribución: Ingles\nDimensiones: 29,17 X 10,17 X 3,6 cm\nSwitches: Redragon Brown",
        img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718548378/RedragondraconicPro_fow2zz.png",
        stock: 4,
        category: "Perifericos",
        subcategory: "Teclados",
    },
    {
        id: 18,
        title: "Redragon K552 Kumara",
        maker: "Redragon",
        price: 57000,
        description: "Diseño del Teclado: Tenkeyless 80%\nInterfaz: USB\nDistribución: Español\nDimensiones: 37,5 X 15,5 X 4,3 cm\nSwitches: Outemu Blue",
        img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718548934/RedragonK552Kumara_imhnxt.jpg",
        stock: 5,
        category: "Perifericos",
        subcategory: "Teclados",
    },
    {
        id: 19,
        title: "Logitech G213",
        maker: "Logitech",
        price: 93500,
        description: "Diseño del Teclado: Estándar\nInterfaz: USB 2.0\nDistribución: Español\nDimensiones: 452 X 218 X 33 mm\nPeso: 1000g",
        img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718549297/LogitechG213_qbera1.jpg",
        stock: 3,
        category: "Perifericos",
        subcategory: "Teclados",
    },
    {
        id: 20,
        title: "Genius DX-110",
        maker: "Genius",
        price: 6450,
        description: "Sensor: óptico\nInterfaz: cable USB\nLargo cable: 1.5m\nResolución: 1000 dpi\nDimensiones: 105 x 60 x 37 mm\nPeso: 85g",
        img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718551115/GeniusDX110_kumj4p.jpg",
        stock: 10,
        category: "Perifericos",
        subcategory: "Mouses",
    },
    {
        id: 21,
        title: "Logitech M280",
        maker: "Logitech",
        price: 19500,
        description: "Conexión: inalámbrica 2.4Ghz\nSensor: Láser\nPilas: 1 AA\nResolución: 1000 dpi\nDimensiones: 105,4 x 67,9 x 38,4 mm\nPeso: 91,0g",
        img: "https://res.cloudinary.com/dqcn00akv/image/upload/v1718551115/LogitechM280_eroggb.jpg",
        stock: 12,
        category: "Perifericos",
        subcategory: "Mouses",
    },
]